Update 5.2.0.md
mono/website pull request #286
Opened 2017-05-11 20:20 UTC by alexanderkyte

2017-05-16 23:28 UTC, akoeplinger requested changes
also needs a rebase :)

2017-05-16 23:28 UTC, akoeplinger commented on docs/about-mono/releases/5.2.0.md
> +An initial implementation of the name mangler was created. It associates with each method a unique string that captures the unique attributes of the method. If two methods have the same mangled repre
I don't think a typical Mono user knows what the "mangler" is after reading this. Can you add some more details about why/where it is needed and when/how someone might want to use it?

2017-05-16 23:28 UTC, akoeplinger commented on docs/about-mono/releases/5.2.0.md
> +The g_getenv and g_setenv are neither threadsafe nor reentrant. Subsequent calls to g_getenv can cause previous strings returned from it to point to garbage memory. This was leading to issues with Sy
with `serious API change` do you mean for embedders? this should have more details about what to change then.

2017-05-25 03:39 UTC, alexanderkyte commented
Comments addressed

2017-05-29 09:12 UTC, merged