Rename release channels to preview, stable and vs
mono/website pull request #346
Opened 2018-02-13 18:04 UTC by luhenry

2018-02-13 18:35 UTC, directhex commented
```
  *  linking to /download/alpha#download-lin, but download-lin does not exist (line 107)
     <a href="/download/alpha#download-lin">alpha</a>
```

I don't know what Travis is talking about. The anchors haven't changed, and the `redirect_from`'s seem fine too? @akoeplinger?

2018-02-13 22:47 UTC, akoeplinger requested changes
few small comments, otherwise looks good!

2018-02-13 22:47 UTC, akoeplinger commented on download/stable.html
> +  - /download/beta/
beta stuff should be moved to preview.html

2018-02-13 22:47 UTC, akoeplinger commented on download/vs.html
> +    <p style="padding: 0 20px"><b>In the VS release channel are packages which are shipped as part of a Visual Studio for Mac release, they are the most stable but also the least frequently updated p
`In the VS release channel are packages` -> `The VS release channel contains packages`

2018-02-13 22:47 UTC, akoeplinger commented on _posts/2017-05-15-mono-5-0-is-out.md
> +Mono 5.0 is out in the [stable channel](/download/stable) !
please add a trailing `/` to all urls to save a redirect

2018-02-13 22:47 UTC, akoeplinger commented on download/stable.html
> -  - /Download/
this should be kept

2018-02-14 01:03 UTC, akoeplinger approved these changes

2018-02-14 01:04 UTC, merged