Added souper post
mono/website pull request #421
Opened 2018-11-21 21:18 UTC by alexanderkyte

2018-11-21 22:24 UTC, lambdageek requested changes
Toplevel items:
1. Needs an introduction paragraph and a conclusion paragraph that both summarize what this blog post is about.
2. Address either "you" or "the programmer" or "people", not all three.
3. The discussion about LLVM and AOT compilers in general vs JITs is very vague.  I can't decide if you need more details or fewer.  Maybe just assert that optimization passes allow AOT to be competitive with JITs, if the optimizations actually get a chance to apply.
4. Clearer explanation of who may want to try this, and what they should do after they try it.

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +users live with the performance characteristics of a given policy, we
```suggestion
users to live with the performance characteristics of a given policy, we
```

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +It can analyze your program globally and tell things that you could
```suggestion
LLVM's optimization passes can analyze your program globally and tell things that you could
```

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +never check yourself manually as a programmer before each commit.
In the previous paragraph you talk about "people", in this paragraph it is "you"/"yourself".  In the last couple of paragraphs it is "those people" and "they".  I would recommend to pick one.  "You" is probably the most casual tone; a generic "the programmer"/"they" would be closer to a more professional/academic tone.

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +of inefficiency that it looks for, and we don't get an optimization.
"pattern of inefficiency" is an interesting term (and I actually found a couple of interesting papers that use that term), but  "optimization blocker" has way more relevant search hits.

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +of inefficiency that it looks for, and we don't get an optimization.
On the other hand, "optimization blocker" makes it sound like Mono is actively butting heads with LLVM.  More likely we just don't annotate our LLVM IR in a way where LLVM can apply all of its optimization.

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +really spending time optimizing it. Low-hanging fruit and dumper fires
```suggestion
really spending time optimizing it. Low-hanging fruit and dumpster fires
```

This is really vague.  Maybe give some (brief) examples?

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +The solution to some manifestations of this problem is the use of
> some manifestations of this problem

vague and wishy-washy.  Also we're two paragraphs removed from the place where you briefly alluded to what the problem is (in the middle of a paragraph).

Say clearly what problem superoptimizers are solving for Mono.  Say it at the beginning of a paragraph.  Maybe add sections so there's a clear separation between the first section - where you're describing the performance difference between our AOT and JIT modes -  and the second section which is about the proposed solution.

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +of randomly generated native code and checks how it behaves
```suggestion
of random native code and checks whether it behaves
```

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +code sequence than the compiler while keeping behavior exactly the
```suggestion
code sequence than what the programmer wrote while keeping behavior exactly the
```

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +correctly. The computational effort involved has kept it from being
```suggestion
correctly. The computational effort involved has kept superoptimization from being
```

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +used very often. Computers get faster and theorems get better, and we
```suggestion
used very often. As computers got faster, we
```

(I'm not sure what `and theorems got better` means.  Do you mean that we now have more accurate ways of specifying program behavior in a manner that can guide superoptimization in generating code?)

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +computes better IR. This can sometimes take a lot of time, and the
```suggestion
compute better IR. This can sometimes take a lot of time, and the
```

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +conventional pattern matching. That said, Souper offers the ability to
> conventional pattern matching

That's... really not how a lot of high level optimizations work.  How about just "conventional techniques" since that will convey the point you want to make

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +drop in for clang and to generate the code that is run. Some folks
```suggestion
drop in for LLVM's optimizer and backend and to emit the final superoptimized machine code. Some folks
```

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +compile time is longer.
This isn't the tone I'd use, but I'm not writing this blog.  If you want to keep it jokey and casual, maybe addressing "you" throughout the whole post is a good way to go.

Also maybe bullet points here?  People will skim long posts but pause over bulletpoints - it'll give them a place to anchor to see if this is relevant to what they want to do.

Something like:
```
   Superoptimization may be for you if:
   * you want to live life in the fast lane (and you trust machine code generated by Souper)
   * you want to see just how fast Mono could run your code if the performance of generated code was not a factor
     (but remember that writing efficient high-level code that uses performant algorithms still matters!)
   * you are willing to pay the penalty of longer compilation times.
```

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +create wrappers for things to replace that level of indirection.
> create wrappers for things to replace that level of indirection.

Vague (and also wrong?). "wrappers for things" is really unclear.

Also "replace that level of indirection" doesn't make sense to me - the AOT compiler is the one that has to _introduce_ an indirection, because it cannot just refer directly to an object in memory - because it doesn't know where it would be.

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +and the small.
> It has a lot of optimizations both in the big and the small.

Are you talking about interprocedural optimizations and peephole optimizations?  I'm not sure what this sentence is about.

Also I'm not sure what this paragraph is for.

I think this paragraph is supposed to reassure me that although AOT cannot play the same tricks as a JIT with directly addressing the actual objects that arise during the run of a program, LLVMs optimizations make up for it by generating better code than a JIT can since LLVM can spend more time analyzing the overall structure of the program.

Is that what you would like to get across?

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +never check yourself manually as a programmer before each commit.
> tell things that you could never check yourself manually as a programmer before each commit.

Confusing why commits enter into it.  Also checking - I don't think of optimization passes as checking anything.

I think you want to say that a compiler is able to see through abstractions that programmers create in order to keep code manageable.  As programmers we use abstract data types and interfaces to separate concerns in our programs in order to make it easier for ourselves and our collaborators to reason about the behavior of our code.  We may use a function call to access a member of a data structure to maintain the illusion of abstraction because otherwise our code would be  a mess that is impossible to refactor or to explain.  A compiler on the other hand, is free to look through abstractions when generating code - it can inline accessor methods and discover recurring subexpressions, it can reorder data accesses or to replace expensive re-computations by incremental updates.

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +technical maturity while interoperating with the industry standard
> relative technical maturity

> industry standard

So we care because it's pretty stable and can easily plug into tools that we use?

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +Just-In-Time compiler, or an Ahead-Of-Time compiler.
I think you need an introductory paragraph that actually introduces what we're doing (and the relative maturity of it:  is it an experiment, something we're going to ship soon, something that we shipped 12 months ago?) before diving into tradeoffs and details.

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +Mono will then allow souper to step in during the middle of the LLVM
```suggestion
Mono will then allow Souper to step in during the middle of the LLVM
```

2018-11-21 22:24 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +found.
Add a conclusion paragraph.

Is this a call to action?  Is it something we want people to try and report back to us?   Is this something we did just to see if it's possible?  Does it demonstrate something about Mono's flexibility?  Are we abandoning the traditional LLVM backend?

2018-11-21 22:26 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +The Mono C# VM is a rather nimble beast. Rather than requiring all
```suggestion
The Mono .NET VM is a rather nimble beast. Rather than requiring all
```

2018-11-21 23:03 UTC, alexanderkyte commented on _posts/2018-11-21-souper.md
> +found.
This does not supplant all of the optimization LLVM does, but operates as a pass on their IR. Superoptimization operates at the level of peephole optimization. I mentioned above that more big-picture (interprocedural) optimizations are still our responsibility and the responsibility of LLVM. I can be more clear about that.

2018-12-05 22:35 UTC, alexanderkyte commented
@lambdageek I've edited it significantly to add the perspective you were looking for. Let me know if you spot any further issues with voice. I use passive voice in a few places, but they all seem clearer for it.

2018-12-05 22:57 UTC, lambdageek requested changes
Almost there!  Looking very good now.

2018-12-05 22:57 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +using our LLVM backend with these new community passes. Feedback about the
what are "new community passes"?

2018-12-05 22:57 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +flexibility as an embedded runtime. Embedders using mono should consider
> This speaks to Mono's flexibility as an embedded runtime.

Does it?  Feels more like it speak's to LLVM's flexibility as a compiler framework.

2018-12-05 22:57 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +conventional pattern matching. That said, Souper offers the ability to
I still don't like "conventional pattern matching" as a characterization of traditional compiler optimizations.

2018-12-05 22:57 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +computes better IR. This can sometimes take a lot of time, and the
Take this grammar fix?

2018-12-05 22:57 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +used very often. Computers get faster and theorems get better, and we
Still not a fan of "theorems get better".  what about "we learn more about compiler theory"?

2018-12-05 22:57 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +correctly. The computational effort involved has kept it from being
Reconsider this?

2018-12-05 22:57 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +code sequence than the compiler while keeping behavior exactly the
grammar fix.

2018-12-05 22:57 UTC, lambdageek commented on _posts/2018-11-21-souper.md
> +of randomly generated native code and checks how it behaves
"generates a ton of randomly generated native code" is kinda clunky.  consider my suggested fix?
also `how`->`whether` is a grammar fix

2018-12-05 23:11 UTC, alexanderkyte commented
how->whether implies that it's a pass/fail check and not an analysis of "the ways in which" it behaves differently.

2018-12-05 23:16 UTC, alexanderkyte commented on _posts/2018-11-21-souper.md
> +code sequence than the compiler while keeping behavior exactly the
I think this is a bit misleading because the programmer didn't write the native code stream that's being compared against.  I can make that more clear though.

2018-12-05 23:27 UTC, alexanderkyte commented on _posts/2018-11-21-souper.md
> +conventional pattern matching. That said, Souper offers the ability to
I want to emphasize that they operate by matching a curated set of patterns (constant propagation, dead code elimination, loop unrolling, dataflow to eliminate dead stores) while souper just brute forces a search.

2018-12-06 00:30 UTC, lambdageek approved these changes

2018-12-06 05:53 UTC, alexanderkyte commented
Let me fix that date

2018-12-06 18:06 UTC, merged